#!/bin/python

verbs=[
" (1) etre\n\n to be",
" (2) avoir \n\nto have",
" (3) faire \n\nto do",
" (4) pouvoir \n\nto be able to",
" (5) aller \n\nto go",
" (6) voir \n\nto see",
" (7) vouloir \n\nto want",
" (8) venir \n\nto come",
" (9) devoir \n\nto have to (not falloir)",
" (10) prendre \n\nto take",
" (11) trouver \n\nto find",
" (12) donner \n\nto give",
" (13) falloir \n\nto have to (not devoir)",
" (14) parler \n\nto speak",
" (15) mettre \n\nto put, place (not placer)",

" (16) savoir\n\n to know (not connaitre)",
" (17) passer \n\nto pass",
" (18) regarder \n\nto look",
" (19) aimer \n\nto like",
" (20) croire \n\nto believe",
" (21) demander \n\nto ask",
" (22) rester \n\nto stay",
" (23) repondre \n\nto answer",
" (24) entendre \n\nto hear",
" (25) penser \n\nto think",
" (26) arriver \n\nto arrive",
" (27) connaitre \n\nto know (not savoir)",
" (28) devenir \n\nto become",
" (29) sentir \n\nto feel (not eprouver)",
" (30) sembler \n\nto seem",
  
" (31) tenir \n\nto hold",
" (32) comprendre \n\nto understand",
" (33) rendre \n\nto return (not retourner)",
" (34) attendre \n\nto wait",
" (35) sortir \n\nto go out",
" (36) vivre \n\nto live",
" (37) entrer \n\nto enter",
" (38) reprendre \n\nto resume, to retake",
" (39) porter \n\nto wear",
" (40) chercher \n\nto look for",
" (41) revenir \n\nto come back",
" (42) appeler \n\nto call",
" (43) mourir \n\nto die",
" (44) partir \n\nto leave (not quitter)",
" (45) jeter \n\nto throw (not lancer)",
  
" (46) suivre \n\nto follow",
" (47) ecrire \n\nto write",
" (48) montrer \n\nto show",
" (49) tomber \n\nto fall",
" (50) ouvrir \n\nto open",
" (51) arreter \n\nto stop",
" (52) perdre \n\nto lose",
" (53) commencer \n\nto begin",
" (54) paraitre \n\nto appear (not apparaitre)",
" (55) marcher \n\nto walk",
" (56) lever \n\nto raise (not elever/soulever)",
" (57) permettre \n\nto allow",
" (58) s'asseoir \n\nto sit",
" (59) ecouter \n\nto listen to",
" (60) monter \n\nto go up",
  
" (61) apercevoir \n\nto catch sight of, to notice (not remarquer)",
" (62) recevoir \n\nto receive",
" (63) servir \n\nto serve",
" (64) finir \n\nto finish (not terminer)",
" (65) rire \n\nto laugh",
" (66) crier \n\nto shout",
" (67) jouer \n\nto play",
" (68) tourner \n\nto turn",
" (69) garder \n\nto keep",
" (70) reconnaitre \n\nto recognize",
" (71) dire \n\nto say",
" (72) quitter \n\nto leave (not partir)",
" (73) manger \n\nto eat",
" (74) courir \n\nto run",
" (75) continuer \n\nto continue",
  
" (76) oublier \n\nto forget",
" (77) descendre \n\nto go down",
" (78) cacher \n\nto hide",
" (79) poser \n\nto put",
" (80) tirer \n\nto pull",
" (81) presenter \n\nto present",
" (82) ajouter \n\nto add",
" (83) agir \n\nto act",
" (84) retrouver \n\nto find (again)",
" (85) offrir \n\nto offer",
" (86) apprendre \n\nto learn",
" (87) tuer \n\nto kill",
" (88) retourner \n\nto return (not rendre)",
" (89) rencontrer \n\nto meet",
" (90) envoyer \n\nto send",
  
" (91) dormir \n\nto sleep",
" (92) pousser \n\nto push",
" (93) rappeler \n\nto call back",
" (94) lire \n\nto read",
" (95) changer \n\nto change",
" (96) essayer \n\nto try",
" (97) compter \n\nto count",
" (98) occuper \n\nto occupy",
" (99) expliquer \n\nto explain",
" (100) frapper \n\nto hit",
" (101) travailler \n\nto work",
" (102) obtenir \n\nto get",
" (103) pleurer \n\nto mourn, to cry, to weep",
" (104) repeter \n\nto repeat (not redire)",
" (105) payer \n\nto pay",
  
" (106) apporter \n\nto bring (something)",
" (107) exister \n\nto exist",
" (108) boire \n\nto drink",
" (109) sourire \n\nto smile",
" (110) coucher \n\nto have sex with",
" (111) causer \n\nto cause",
" (112) raconter \n\nto tell",
" (113) serrer \n\nto tighten",
" (114) songer \n\nto daydream, to think, to dream",
" (115) manquer \n\nto miss",
" (116) nommer \n\nto call, to name",
" (117) conduire \n\nto drive",
" (118) saisir \n\nto seize",
" (119) demeurer \n\nto remain",
" (120) remettre \n\nto put back, to lay, to put",
  
" (121) disparaitre \n\nto disappear",
" (122) battre \n\nto beat",
" (123) toucher \n\nto touch",
" (124) apparaitre \n\nto appear (paraitre)",
" (125) souffrir \n\nto suffer",
" (126) fermer \n\nto close",
" (127) accepter \n\nto accept",
" (128) naitre \n\nto be born",
" (129) sauver \n\nto rescue",
" (130) avancer \n\nto advance",
" (131) traverser \n\nto cross",
" (132) se souvenir \n\nto remember",
" (133) couvrir \n\nto cover",
" (134) gagner \n\nto win",
" (135) former \n\nto form",

" (136)  plaire \n\nto please", 
" (137)  embrasser \n\nto kiss", 
" (138)  oser \n\nto dare", 
" (139)  empecher \n\nto prevent (not prevenir)", 
" (140)  refuser \n\nto refuse", 
" (141)  decider \n\nto decide", 
" (142)  produire \n\nto produce", 
" (143)  charger \n\nto load", 
" (144)  meler \n\nto mingle", 
" (145)  esperer \n\nto hope", 
" (146)  cesser \n\nto cease", 
" (147)  ressembler \n\nto look like", 
" (148)  chanter \n\nto sing", 
" (149)  approcher \n\nto approach", 
" (150)  prier \n\nto pray", 
        
" (151) echapper \n\nto escape (not fuir, not eviter)",
" (152) glisser \n\nto slide",
" (153) briller \n\nto shine",
" (154) bruler \n\nto burn",
" (155) placer \n\nto place (not mettre)",
" (156) juger \n\nto judge",
" (157) atteindre \n\nto reach (not parvenir)",
" (158) annoncer \n\nto announce",
" (159) elever \n\nto raise (not lever/soulever)",
" (160) acheter \n\nto buy",
" (161) mener \n\nto lead (not diriger)",
" (162) preparer \n\nto prepare",
" (163) assurer \n\nto insure",
" (164) deviner \n\nto guess",
" (165) considerer \n\nto consider",
  
" (166) appartenir \n\nto belong",
" (167) representer \n\nto represent",
" (168) tromper \n\nto deceive, to cheat on",
" (169) vendre \n\nto sell",
" (170) craindre \n\nto fear",
" (171) emporter \n\nto take, to carry away",
" (172) exprimer \n\nto express",
" (173) rouler \n\nto roll",
" (174) posseder \n\nto own",
" (175) se reveiller \n\nto wake up",
" (176) aider \n\nto help",
" (177) decouvrir \n\nto discover",
" (178) choisir \n\nto choose",
" (179) prononcer \n\nto pronounce",
" (180) rever \n\nto dream",
  
" (181) appuyer \n\nto press",
" (182) etendre \n\nto stretch",
" (183) trembler \n\nto shiver",
" (184) defendre \n\nto defend",
" (185) creer \n\nto create",
" (186) maintenir \n\nto maintain",
" (187) indiquer \n\nto indicate",
" (188) promettre \n\nto promise",
" (189) reveler \n\nto reveal",
" (190) abandonner \n\nto give up (not renoncer)",
" (191) ignorer \n\nto ignore",
" (192) adresser \n\nto address",
" (193) observer \n\nto observe",
" (194) separer \n\nto separate",
" (195) se marier \n\nto get married",
 
" (196) prevoir \n\nto foresee",
" (197) amener \n\nto bring (someone)",
" (198) obliger \n\nto force (not forcer)",
" (199) eclairer \n\nto light up, to clarify, to enlighten",
" (200) poursuivre \n\nto pursue",
" (201) livrer \n\nto deliver",
" (202) contenir \n\nto contain",
" (203) fuir \n\nto flee, to escape, to avoid (not echapper, not eviter)",
" (204) couler \n\nto flow",
" (205) proposer \n\nto propose",
" (206) eprouver \n\nto feel (not sentir)",
" (207) retenir \n\nto retain",
" (208) attacher \n\nto attach",
" (209) voler \n\nto steal",
" (210) entrainer \n\nto train, to involve",

" (211) surprendre \n\nto surprise",
" (212) briser \n\nto break (not rompre/casser)",
" (213) imaginer \n\nto imagine",
" (214) diriger \n\nto lead (not mener)",
" (215) parvenir \n\nto reach (not atteindre)",
" (216) penetrer \n\nto penetrate",
" (217) remarquer \n\nto notice (not apercevoir)",
" (218) eviter \n\nto avoid (not fuir)",
" (219) etablir \n\nto establish",
" (220) reussir \n\nto succeed",
" (221) pencher \n\nto tilt",
" (222) habiter \n\nto live in",
" (223) entourer \n\nto surround",
" (224) declarer \n\nto declare",
" (225) etonner \n\nto astonish",
 
" (226) dresser \n\nto draw up (not dessiner)",
" (227) durer \n\nto last",
" (228) fixer \n\nto fix",
" (229) desirer \n\nto desire",
" (230) soutenir \n\nto sustain",
" (231) couper \n\nto cut",
" (232) examiner \n\nto examine",
" (233) douter \n\nto doubt",
" (234) retirer \n\nto remove, to take off",
" (235) promener \n\nto go for a walk",
" (236) forcer \n\nto force (not obliger)",
" (237) revoir \n\nto see again",
" (238) remplir \n\nto fill",
" (239) terminer \n\nto finish (not finir)",
" (240) tenter \n\nto tempt",
 
" (241) sonner \n\nto ring",
" (242) composer \n\nto compose",
" (243) enlever \n\nto remove",
" (244) rejoindre \n\nto meet (up with), to join, to catch up with",
" (245) etudier \n\nto study",
" (246) partager \n\nto share",
" (247) chasser \n\nto hunt",
" (248) interrompre \n\nto interrupt",
" (249) eloigner \n\nto move away",
" (250) reduire \n\nto reduce",
" (251) eteindre \n\nto put out",
" (252) recommencer \n\nto start again",
" (253) sauter \n\nto jump",
" (254) plaindre \n\nto pity",
" (255) preferer \n\nto prefer",
 
" (256) subir \n\nto undergo",
" (257) rapporter \n\nto bring back, to bring",
" (258) reflechir \n\nto reflect [thoughts]",
" (259) remercier \n\nto thank",
" (260) deposer \n\nto deposit",
" (261) fumer \n\nto smoke",
" (262) affirmer \n\nto affirm",
" (263) vetir \n\nto clothe",
" (264) accomplir \n\nto fulfil, to accomplish",
" (265) resoudre \n\nto solve",
" (266) plonger \n\nto dive",
" (267) detruire \n\nto destroy",
" (268) interesser \n\nto interest",
" (269) disposer \n\nto arrange (not arranger)",
" (270) verser \n\nto pour",
 
" (271) obeir \n\nto obey",
" (272) desobeir \n\nto disobey",
" (273) lutter \n\nto struggle (not se battre)",
" (274) pretendre \n\nto claim, to pretend",
" (275) construire \n\nto build",
" (276) reconstruire \n\nto rebuild",
" (277) soumettre \n\nto submit",
" (278) peser \n\nto weigh",
" (279) repandre \n\nto spread, to scatter, to spill",
" (280) resister \n\nto resist",
" (281) proteger \n\nto protect",
" (282) enfermer \n\nto lock up",
" (283) creuser \n\nto dig",
" (284) grandir \n\nto grow",
" (285) enfoncer \n\nto break in, to push in, to drive in",
 
" (286) envelopper \n\nto wrap",
" (287) prevenir \n\nto prevent (not empecher)",
" (288) inspirer \n\nto inspire",
" (289) ramasser \n\nto pick up",
" (290) endormir \n\nto put to sleep",
" (291) inventer \n\nto invent",
" (292) presser \n\nto squeeze",
" (293) confier \n\nto entrust",
" (294) effacer \n\nto erase",
" (295) reculer \n\nto move back",
" (296) user \n\nto wear out",
" (297) nourrir \n\nto feed",
" (298) remplacer \n\nto replace",
" (299) souhaiter \n\nto wish",
" (300) signer \n\nto sign",
 
" (301) interroger \n\nto question",
" (302) dominer \n\nto dominate",
" (303) commander \n\nto order, to command, to commission",
" (304) supposer \n\nto suppose",
" (305) depasser \n\nto exceed",
" (306) accuser \n\nto accuse",
" (307) habiller \n\nto dress",
" (308) condamner \n\nto condemn",
" (309) menacer \n\nto threaten",
" (310) ecraser \n\nto crush",
" (311) reclamer \n\nto ask for",
" (312) dessiner \n\nto draw (not dresser)",
" (313) conclure \n\nto conclude",
" (314) lier \n\nto link, to bind",
" (315) admettre \n\nto admit (not avouer)",
 
" (316) remonter \n\nto go back up",
" (317) installer \n\nto install",
" (318) soulever \n\nto lift up, to arouse, to raise (not lever/elever)",
" (319) allumer \n\nto turn on",
" (320) imposer \n\nto impose",
" (321) respirer \n\nto breathe",
" (322) baisser \n\nto lower",
" (323) souffler \n\nto blow",
" (324) attirer \n\nto attract",
" (325) preter \n\nto lend",
" (326) amuser \n\nto amuse",
" (327) eclater \n\nto burst",
" (328) reunir \n\nto gather",
" (329) traiter \n\nto treat",
" (330) engager \n\nto hire",
 
" (331) employer \n\nto employ",
" (332) marquer \n\nto mark",
" (333) prouver \n\nto prove",
" (334) importer \n\nto import",
" (335) exiger \n\nto require",
" (336) reposer \n\nto rest",
" (337) danser \n\nto dance",
" (338) saluer \n\nto greet",
" (339) accorder \n\nto grant",
" (340) achever \n\nto complete",
" (341) avouer \n\nto admit (not admettre)",
" (342) distinguer \n\nto distinguish",
" (343) emmener \n\nto take along",
" (344) agiter \n\nto shake",
" (345) hesiter \n\nto hesitate",
 
" (346) attaquer \n\nto attack",
" (347) respecter \n\nto respect",
" (348) pendre \n\nto hang, to dangle",
" (349) supporter \n\nto support",
" (350) figurer \n\nto appear (intr) / to represent, to show, to depict (tran) / to be an extra, to do a walk-on part",
" (351) profiter \n\nto take advantage",
" (352) calmer \n\nto calm down",
" (353) satisfaire \n\nto satisfy (not contenter)",
" (354) valoir \n\nto be worth",
" (355) signifier \n\nto mean",
" (356) inquieter \n\nto worry",
" (357) assister \n\nto assist",
" (358) inviter \n\nto invite",
" (359) dechirer \n\nto tear",
" (360) risquer \n\nto risk",
 
" (361) parcourir \n\nto travel all over",
" (362) rejeter \n\nto reject",
" (363) renoncer \n\nto give up (not abandonner)",
" (364) veiller \n\nto watch over",
" (365) transformer \n\nto transform",
" (366) contenter \n\nto satisfy (not satisfaire)",
" (367) meriter \n\nto deserve",
" (368) precipiter \n\nto hasten",
" (369) rompre \n\nto break (not briser/casser)",
" (370) etouffer \n\nto suffocate",
" (371) animer \n\nto bring life to",
" (372) casser \n\nto break (not rompre/briser)",
" (373) fonder \n\nto found",
" (374) franchir \n\nto get over",
" (375) abattre \n\nto slaughter",
 
" (376) discuter \n\nto discuss",
" (377) fatiguer \n\nto tire",
" (378) consentir \n\nto consent",
" (379) regretter \n\nto regret",
" (380) vaincre \n\nto defeat",
" (381) consulter \n\nto consult",
" (382) hair \n\nto hate (not detester)",
" (383) repousser \n\nto push away",
" (384) executer \n\nto execute",
" (385) exposer \n\nto display",
" (386) voyager \n\nto travel",
" (387) renverser \n\nto knock down",
" (388) rassurer \n\nto reassure",
" (389) retomber \n\nto fall again",
" (390) decrire \n\nto describe",
 
" (391) mentir \n\nto lie",
" (392) abolir \n\nto abolish",
" (393) adorer \n\nto adore",
" (394) admirer \n\nto admire",
" (395) agacer \n\nto annoy",
" (396) comparer \n\nto compare",
" (397) conquerir \n\nto conquer",
" (398) defaire \n\nto undo",
" (399) demolir \n\nto demolish",
" (400) dejeuner \n\nto lunch",
" (401) diner \n\nto dine",
" (402) diminuer \n\nto diminish",
" (403) elire \n\nto elect",
" (404) grimper \n\nto climb",
" (405) introduire \n\nto introduce",
 
" (406) jurer \n\nto swear",
" (407) jouir \n\nto enjoy",
" (408) lancer \n\nto throw (not jeter)",
" (409) laver \n\nto wash",
" (490) nager \n\nto swim",
" (411) naviguer \n\nto navigate",
" (412) pleuvoir \n\nto rain",
" (413) refaire \n\nto redo",
" (414) suggerer \n\nto suggest",
" (415) trahir \n\nto betray",
" (416) utiliser \n\nto use",
" (417) verifier \n\nto check",
" (418) se facher \n\nto get angry",
" (419) enterrer \n\nto bury",
" (420) enregistrer \n\nto record",
 
" (421) divorcer \n\nto get divorced",
" (422) corriger \n\nto correct",
" (423) celebrer \n\nto celebrate",
" (424) bavarder \n\nto chat",
" (425) avoir besoin de \n\nto need",
" (426) augmenter \n\nto increase",
" (427) blamer \n\nto blame",
" (428) avoir raison \n\nto be right",
" (429) conseiller \n\nto advise",
" (430) consommer \n\nto consume",
" (431) denoncer \n\nto denounce",
" (432) echouer \n\nto fail",
" (433) imprimer \n\nto print",
" (434) encourager \n\nto encourage",
" (435) geler \n\nto freeze",
 
" (436) gouter \n\nto taste",
" (437) guerir \n\nto cure",
" (438) informer \n\nto inform",
" (439) insister \n\nto insist",
" (440) ralentir \n\nto slow down",
" (441) redire \n\nto repeat, to say again (not repeter)",
" (442) detester \n\nto hate (not hair)",
" (443) negocier \n\nto negotiate",
" (444) enseigner \n\nto teach",
" (445) detenir \n\nto hold, to detain",
" (446) attraper \n\nto catch",
" (447) controler \n\nto control",
" (448) convaincre \n\nto convince",
" (449) mesurer \n\nto measure",
" (450) mouiller \n\nto get something wet",

]
