#!/bin/python

verbs=[
" etre\n\n to be",
" avoir \n\nto have",
" faire \n\nto do",
" pouvoir \n\nto be able to",
" aller \n\nto go",
" voir \n\nto see",
" vouloir \n\nto want",
" venir \n\nto come",
" devoir \n\nto have to (not falloir)",
" prendre \n\nto take",
" trouver \n\nto find",
" donner \n\nto give",
" falloir \n\nto have to (not devoir)",
" parler \n\nto speak",
" mettre \n\nto put, place (not placer)",

" savoir\n\n to know (not connaitre)",
" passer \n\nto pass",
" regarder \n\nto look",
" aimer \n\nto like",
" croire \n\nto believe",
" demander \n\nto ask",
" rester \n\nto stay",
" repondre \n\nto answer",
" entendre \n\nto hear",
" penser \n\nto think",
" arriver \n\nto arrive",
" connaitre \n\nto know (not savoir)",
" devenir \n\nto become",
" sentir \n\nto feel (not eprouver)",
" sembler \n\nto seem",
  
" tenir \n\nto hold",
" comprendre \n\nto understand",
" rendre \n\nto return (not retourner)",
" attendre \n\nto wait",
" sortir \n\nto go out",
" vivre \n\nto live",
" entrer \n\nto enter",
" reprendre \n\nto resume, to retake",
" porter \n\nto wear",
" chercher \n\nto look for",
" revenir \n\nto come back",
" appeler \n\nto call",
" mourir \n\nto die",
" partir \n\nto leave (not quitter)",
" jeter \n\nto throw (not lancer)",
  
" suivre \n\nto follow",
" ecrire \n\nto write",
" montrer \n\nto show",
" tomber \n\nto fall",
" ouvrir \n\nto open",
" arreter \n\nto stop",
" perdre \n\nto lose",
" commencer \n\nto begin",
" paraitre \n\nto appear (not apparaitre)",
" marcher \n\nto walk",
" lever \n\nto raise (not elever/soulever)",
" permettre \n\nto allow",
" s'asseoir \n\nto sit",
" ecouter \n\nto listen to",
" monter \n\nto go up",
  
" apercevoir \n\nto catch sight of, to notice (not remarquer)",
" recevoir \n\nto receive",
" servir \n\nto serve",
" finir \n\nto finish (not terminer)",
" rire \n\nto laugh",
" crier \n\nto shout",
" jouer \n\nto play",
" tourner \n\nto turn",
" garder \n\nto keep",
" reconnaitre \n\nto recognize",
" dire \n\nto say",
" quitter \n\nto leave (not partir)",
" manger \n\nto eat",
" courir \n\nto run",
" continuer \n\nto continue",
  
" oublier \n\nto forget",
" descendre \n\nto go down",
" cacher \n\nto hide",
" poser \n\nto put",
" tirer \n\nto pull",
" presenter \n\nto present",
" ajouter \n\nto add",
" agir \n\nto act",
" retrouver \n\nto find (again)",
" offrir \n\nto offer",
" apprendre \n\nto learn",
" tuer \n\nto kill",
" retourner \n\nto return (not rendre)",
" rencontrer \n\nto meet",
" envoyer \n\nto send",
  
" dormir \n\nto sleep",
" pousser \n\nto push",
" rappeler \n\nto call back",
" lire \n\nto read",
" changer \n\nto change",
" essayer \n\nto try",
" compter \n\nto count",
" occuper \n\nto occupy",
" expliquer \n\nto explain",
" frapper \n\nto hit",
" travailler \n\nto work",
" obtenir \n\nto get",
" pleurer \n\nto mourn, to cry, to weep",
" repeter \n\nto repeat (not redire)",
" payer \n\nto pay",
  
" apporter \n\nto bring (something)",
" exister \n\nto exist",
" boire \n\nto drink",
" sourire \n\nto smile",
" coucher \n\nto have sex with",
" causer \n\nto cause",
" raconter \n\nto tell",
" serrer \n\nto tighten",
" songer \n\nto daydream, to think, to dream",
" manquer \n\nto miss",
" nommer \n\nto call, to name",
" conduire \n\nto drive",
" saisir \n\nto seize",
" demeurer \n\nto remain",
" remettre \n\nto put back, to lay, to put",
  
" disparaitre \n\nto disappear",
" battre \n\nto beat",
" toucher \n\nto touch",
" apparaitre \n\nto appear (paraitre)",
" souffrir \n\nto suffer",
" fermer \n\nto close",
" accepter \n\nto accept",
" naitre \n\nto be born",
" sauver \n\nto rescue",
" avancer \n\nto advance",
" traverser \n\nto cross",
" se souvenir \n\nto remember",
" couvrir \n\nto cover",
" gagner \n\nto win",
" former \n\nto form",
  
" echapper \n\nto escape (not fuir, not eviter)",
" glisser \n\nto slide",
" briller \n\nto shine",
" bruler \n\nto burn",
" placer \n\nto place (not mettre)",
" juger \n\nto judge",
" atteindre \n\nto reach (not parvenir)",
" annoncer \n\nto announce",
" elever \n\nto raise (not lever/soulever)",
" acheter \n\nto buy",
" mener \n\nto lead (not diriger)",
" preparer \n\nto prepare",
" assurer \n\nto insure",
" deviner \n\nto guess",
" considerer \n\nto consider",
  
" appartenir \n\nto belong",
" representer \n\nto represent",
" tromper \n\nto deceive, to cheat on",
" vendre \n\nto sell",
" craindre \n\nto fear",
" emporter \n\nto take, to carry away",
" exprimer \n\nto express",
" rouler \n\nto roll",
" posseder \n\nto own",
" se reveiller \n\nto wake up",
" aider \n\nto help",
" decouvrir \n\nto discover",
" choisir \n\nto choose",
" prononcer \n\nto pronounce",
" rever \n\nto dream",
  
" appuyer \n\nto press",
" etendre \n\nto stretch",
" trembler \n\nto shiver",
" defendre \n\nto defend",
" creer \n\nto create",
" maintenir \n\nto maintain",
" indiquer \n\nto indicate",
" promettre \n\nto promise",
" reveler \n\nto reveal",
" abandonner \n\nto give up (not renoncer)",
" ignorer \n\nto ignore",
" adresser \n\nto address",
" observer \n\nto observe",
" separer \n\nto separate",
" se marier \n\nto get married",
  
" prevoir \n\nto foresee",
" amener \n\nto bring (someone)",
" obliger \n\nto force (not forcer)",
" eclairer \n\nto light up, to clarify, to enlighten",
" poursuivre \n\nto pursue",
" livrer \n\nto deliver",
" contenir \n\nto contain",
" fuir \n\nto flee, to escape, to avoid (not echapper, not eviter)",
" couler \n\nto flow",
" proposer \n\nto propose",
" eprouver \n\nto feel (not sentir)",
" retenir \n\nto retain",
" attacher \n\nto attach",
" voler \n\nto steal",
" entrainer \n\nto train, to involve",

]
